title: Hi, I’m Sam
email: sam@soff.es
author: Sam Soffes
description: >-
  This is my blog. I also have a <a href="https://soff.es/" rel="external">website thing</a>.
baseurl: ""
url: "https://soffes.blog"
twitter_username: soffes
github_username:  soffes
timezone: America/Los_Angeles
encoding: utf-8
strict_front_matter: true
permalink: /:title
paginate: 5
paginate_path: "/:num"
exclude:
  - README.md
markdown: Custom
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-paginate
